//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeForFriday
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int userid { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string loginID { get; set; }
        public string loginPassword { get; set; }
        public string Email_Address { get; set; }
        public string Home_Address { get; set; }
        public Nullable<int> Phone { get; set; }
        public string Portrait { get; set; }
    }
}
